# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74950f55659341419fdcd51f7e8198763be3acf9ada61bd4c0be357880026756aecff7b4f5b98f1128e0864b70703a811a8f9a1d43297db542a9dc1ed6b374be

test:
  secret_key_base: 4c7f0e542d645675976548d7fd8f486cb8f20c7b293ddeb56598f4915a7849d22c67ee2b92cc13dfae6ea5e1ecaeb1e64b92803c9574f7833b5432a5905ab001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
